name: release

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, windows-2022]
        version: [6.2.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: msys2/setup-msys2@v2
        if: startsWith(matrix.os, 'windows')
        with:
          path-type: strict
          install: git make cmake ruby python ninja gcc
          msystem: UCRT64

      - name: Set environment variables
        run: echo "ASSET=qt-${{ matrix.os }}-${{ matrix.version }}.tar.gz">>$GITHUB_ENV
        if: startsWith(matrix.os, 'windows') == false
      - name: Set environment variables
        if: startsWith(matrix.os, 'windows')
        run: echo "ASSET=qt-${{ matrix.os }}-${{ matrix.version }}.tar.gz">>$GITHUB_ENV
        shell: msys2 {0}

      - name: Clone from source
        run: git clone https://code.qt.io/qt/qt5.git -b v${{ matrix.version }} qt_src

      - name: Initialize source
        run: cd qt_src && perl init-repository --module-subset=qtbase

      - name: Compress for shipping
        run: cd qt_src && tar -zcvf ${{ env.ASSET }} * && mv ${{ env.ASSET }} ..

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          tag_name: v0.0.1
          files: ${{ env.ASSET }}
          generate_release_notes: true

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true
